### ISSUE TITLE
make: *** [build_mesos_image] Error 2

### ISSUE THREAD

**Issue by simoneroselli** [Capgemini/mesos-ui#67]
```
~$ git clone https://github.com/Capgemini/mesos-ui.git mesos-ui
~$ cd mesos-ui/
~$ npm install
~$ export MESOS_VERSION="0.25.0"
~$ export MESOS_UI_VERSION="0.1.1"
~$ make
...
[14:40:18] Finished 'bundle' after 15 s
[14:40:18] Finished 'build' after 15 s
sed "s/VERSION/0.25.0/g" DockerfileMesos > TempDockerfile
sed: can't read DockerfileMesos: No such file or directory
make: *** [build_mesos_image] Error 2
```

In the end, DockerfileMesos file is not present in the checkout
```
~$ ls
build            Dockerfile  gulpfile.babel.js  marathon.json  package.json  src             webpack.config.js
CONTRIBUTING.MD  docs        LICENSE            node_modules   README.md     TempDockerfile  wercker.yml
```

Thanks for the support

**Comment by enxebre** [comment]
Hi @simoneroselli, what are you trying to do exactly?
you can just use the images in https://hub.docker.com/r/capgemini/mesos-ui/tags/

If for some reason you want to build it by yourself the Mesos version you are using is incorrect. 
Mesos version should be something like 
```MESOS_VERSION=0.25.0-0.2.70.ubuntu1404```
check https://hub.docker.com/r/mesosphere/mesos-master/tags/

Also if you are trying to build and old version e.g '0.1.1' you'd need to checkout to that version of the code first which is why you are having ```can't read DockerfileMesos: No such file or directory.```

I recommend you either use the latest versions from dockerhub or build the latest version.

Cheers

**Comment by simoneroselli** [comment]
Yes, the mesos version syntax was my problem

Thank you very much
